import type { Metadata } from "next";
import Link from "next/link";
import { buildMetadata, pageSeo } from "@/lib/seo";
export const metadata: Metadata = buildMetadata(pageSeo["/ai-agents"]);
export default function AIPage() {
  return <div className="rebuild-page">
    <section className="rebuild-hero"><p className="rebuild-kicker">AI workflow support</p><h1>Useful assistance, with a person responsible.</h1><p className="rebuild-lead">We can assess where AI assistance fits a repeatable task, what information it needs and how your team will check its output. The starting point is a clear process.</p><Link className="rebuild-button" href="/contact">Discuss a use case</Link></section>
    <section className="rebuild-section"><h2 className="rebuild-section-heading">Examples worth exploring.</h2><div className="rebuild-grid"><article className="rebuild-panel"><h3>Summarising information</h3><p>Prepare a first-pass summary of suitable records for a team member to check.</p></article><article className="rebuild-panel"><h3>Drafting follow-up</h3><p>Help prepare an initial response using the agreed context, with human review before sending.</p></article><article className="rebuild-panel"><h3>Preparing for a conversation</h3><p>Organise relevant notes and questions so a team member can make an informed decision.</p></article></div><p>Availability and suitability depend on your data, software and the agreed scope. These examples are not included features of every website or CRM package.</p></section>
    <section className="rebuild-section"><h2 className="rebuild-section-heading">Set the boundaries first.</h2><ul className="rebuild-list"><li>Use only the information required for the task.</li><li>Agree which provider and systems will handle the data.</li><li>Name the person responsible for checking output.</li><li>Test errors, missing information and the fallback process.</li><li>Agree usage costs and ongoing review before launch.</li></ul><p>AI output can be wrong. Customer-facing messages and important decisions need an appropriate review process.</p></section>
    <section className="rebuild-section"><h2 className="rebuild-section-heading">Get the foundations in place.</h2><p>If contact records, ownership or follow-up are unclear, improving the underlying CRM process may be the more useful first step.</p><Link className="rebuild-text-link" href="/crm">Explore CRM projects →</Link>{" "}<Link className="rebuild-text-link" href="/data-handling">Data handling →</Link>{" "}<Link className="rebuild-text-link" href="/technical-review">Request a technical review →</Link></section>
    <section className="rebuild-section"><h2 className="rebuild-section-heading">Bring us a task, not a technology brief.</h2><p>Describe the work your team repeats and the result you need. We can discuss whether AI, a simpler automation or a process change is appropriate.</p><Link className="rebuild-button" href="/contact">Discuss a use case</Link></section>
  </div>;
}
