import { buildMetadata, pageSeo } from "@/lib/seo";
import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { offers } from "@/components/rebuild/offers";
import { OfferFaq, OfferPrice } from "@/components/rebuild/OfferPage";

export const metadata: Metadata = buildMetadata(pageSeo["/pricing"]);

const questions = [
  { question: "What are the monthly hours for?", answer: "They cover the small changes, support or configuration work included in your package. Larger requests are scoped separately. Unused hours do not roll over into the following month." },
  { question: "Are defect fixes taken from the change allowance?", answer: "Fixing work that does not meet the agreed acceptance criteria is treated separately from requests for new or changed functionality. The project agreement sets out the applicable warranty and support terms." },
  { question: "Who owns our domain and data?", answer: "We set out domain access, website rights, data export and any platform licences in the project agreement. We will explain those arrangements before you commit." },
  { question: "What happens if we stop the monthly service?", answer: "The included hosting, platform access and care end in line with your agreement. Before the service ends, we agree the relevant export and handover steps. Any outstanding implementation balance remains payable, and additional migration assistance may need a separate quote." },
  { question: "Are there guaranteed results?", answer: "We agree deliverables and acceptance checks for the work. We do not guarantee a number of leads, a search ranking or a revenue increase." },
  { question: "Can you quote a project outside these packages?", answer: "Yes. These are starting scopes. Tell us what you need and we will confirm whether a package fits or whether discovery and a custom proposal would be more appropriate." },
];

export default function PricingPage() {
  return <div className="rebuild-page">
    <section className="rebuild-hero"><p className="rebuild-kicker">Pricing</p><h1>Clear prices for a defined starting scope.</h1><p className="rebuild-lead">Choose a website project, a CRM setup or both together. Each package separates the initial implementation from the service that continues after launch.</p><p className="mt-6 max-w-2xl text-sm">No VAT is charged. We confirm your requirements, included scope and total price in writing before work begins.</p></section>
    <section className="rebuild-section" aria-label="Website and CRM packages"><div className="rebuild-grid">
      {offers.slice(0, 3).map((offer) => <article className="rebuild-panel flex flex-col" id={offer.slug} key={offer.slug}>
        <p className="rebuild-kicker">{offer.packageName}</p><h2 className="mb-6">{offer.name}</h2><OfferPrice offer={offer} /><p className="mt-6">{offer.audience}</p>
        <ul className="rebuild-list my-6">{offer.includes.map((item) => <li key={item}>{item}</li>)}</ul><p className="text-sm">{offer.care}</p>
        <div className="mt-auto pt-7"><p className="mb-5 text-sm">Implementation + 12 service months: <strong>{offer.annual}</strong>.</p><Link href={offer.href} className="rebuild-button">{offer.cta}<ArrowRight size={16} aria-hidden="true" /></Link><Link href={`/${offer.slug}`} className="rebuild-text-link mt-4 inline-flex">Full {offer.name.toLowerCase()} scope</Link></div>
      </article>)}
    </div><p className="mt-6 text-sm">The 12-month figures are cost comparisons, not minimum service terms. Additional systems, complex migration and custom features are quoted separately.</p></section>
    <section className="rebuild-section"><div className="rebuild-grid-two"><div><p className="rebuild-kicker">Also available</p><h2 className="rebuild-section-heading">Ecommerce</h2><p className="rebuild-lead">A defined online shop with straightforward product and delivery requirements.</p><div className="mt-6"><OfferPrice offer={offers[3]} /></div><Link href="/contact?service=ecommerce" className="rebuild-button mt-7">Discuss your online shop<ArrowRight size={18} aria-hidden="true" /></Link></div><div><ul className="rebuild-list">{offers[3].includes.map((item) => <li key={item}>{item}</li>)}</ul><p className="mt-5">{offers[3].care}</p><p className="mt-4">{offers[3].exclusions}</p><p className="mt-4 text-sm">Implementation + 12 care months: from <strong>€5,888</strong>, excluding platform costs and agreed extras.</p><Link href="/ecommerce" className="rebuild-text-link mt-5 inline-flex">View the ecommerce scope<ArrowRight size={16} aria-hidden="true" /></Link></div></div></section>
    <section className="rebuild-section"><div className="rebuild-grid-two"><h2 className="rebuild-section-heading">How payment works.</h2><div className="space-y-5"><p>For standard projects, 50% of the implementation fee is due at kickoff and 50% at the agreed acceptance point. Monthly service begins when the project goes live.</p><p>Monthly service is billed monthly and continues until cancelled under the agreed terms. The standard notice period is 30 days. We confirm any different payment arrangement before you commit.</p><p>The package figures above show implementation plus 12 service payments to help you compare costs.</p></div></div></section>
    <section className="rebuild-section"><div className="rebuild-grid-two"><div><p className="rebuild-kicker">More involved projects</p><h2 className="rebuild-section-heading">Discovery before commitment.</h2></div><div className="space-y-5"><p>If your project involves uncertain data, several systems or a more complex process, we start with paid discovery.</p><p>Discovery costs <strong>€750</strong>. You receive a process map, a review of the relevant data and systems, and an implementation scope or estimate. The fee is credited against an implementation accepted within 30 days of the discovery proposal.</p><Link href="/contact" className="rebuild-text-link">Discuss your requirements<ArrowRight size={16} aria-hidden="true" /></Link></div></div></section>
    <section className="rebuild-section"><div className="rebuild-grid-two"><h2 className="rebuild-section-heading">What sits outside the packages?</h2><div className="space-y-5"><p>Common additions include original branding, extensive copywriting, photography, complex migrations, data cleaning, extra users, additional pages, file uploads, third-party connections and new custom features.</p><p>We quote additional work before starting it. Small work outside your allowance can be estimated at €95/hour; larger work receives a separate scope.</p></div></div></section>
    <section className="rebuild-section"><div className="rebuild-grid-two"><div className="rebuild-section-heading"><p className="rebuild-kicker">Before you decide</p><h2 className="rebuild-section-heading">Price, care and ownership.</h2></div><OfferFaq items={questions} /></div></section>
    <section className="rebuild-section"><div className="rebuild-panel"><h2 className="rebuild-section-heading">Find the right scope before choosing a package.</h2><p className="rebuild-lead">Tell us what your business needs to improve. We will discuss the fit, explain the costs and identify any work outside the starting package.</p><Link href="/contact" className="rebuild-button mt-7">Discuss your project<ArrowRight size={18} aria-hidden="true" /></Link></div></section>
  </div>;
}
