import type { Metadata } from "next";
import Link from "next/link";
import { buildMetadata, pageSeo } from "@/lib/seo";
export const metadata: Metadata = buildMetadata(pageSeo["/security"]);
export default function SecurityPage() {
  return <div className="rebuild-page">
    <section className="rebuild-hero"><p className="rebuild-kicker">Security and responsibilities</p><h1>Agree the boundaries before we connect your systems.</h1><p className="rebuild-lead">Website and CRM projects can involve customer information and business-critical tools. Access, responsibilities and review steps need to be clear for the work being delivered.</p><Link className="rebuild-button" href="/technical-review">Request a technical review</Link></section>
    <section className="rebuild-section"><h2 className="rebuild-section-heading">What we discuss with you.</h2><div className="rebuild-grid rebuild-grid-two"><article className="rebuild-panel"><h3>Access and data</h3><p>Which systems and records are needed, who grants access, and when that access should be removed.</p></article><article className="rebuild-panel"><h3>Changes and approvals</h3><p>Who reviews configuration changes and customer-facing actions before they are used.</p></article><article className="rebuild-panel"><h3>Testing and recovery</h3><p>How key journeys will be tested and what the agreed fallback is if a change causes a problem.</p></article><article className="rebuild-panel"><h3>Ongoing responsibility</h3><p>Which responsibilities sit with Ingenium, your team and third-party providers after launch.</p></article></div></section>
    <section className="rebuild-section"><h2 className="rebuild-section-heading">Review the details.</h2><p>The exact controls depend on the systems and agreed project. We do not claim a certification or audit unless it has been completed and documented.</p><ul className="rebuild-list"><li><Link href="/security-review">Our security review process</Link></li><li><Link href="/data-handling">How project data is handled</Link></li><li><Link href="/privacy">Website visitor privacy notice</Link></li><li><Link href="/support">Client support process</Link></li></ul></section>
    <section className="rebuild-section"><h2 className="rebuild-section-heading">Have a specific requirement?</h2><p>Tell us which systems and controls need review before you decide whether the project is a fit.</p><Link className="rebuild-button" href="/technical-review">Request a technical review</Link></section>
  </div>;
}
