import type { Metadata } from "next";
import Link from "next/link";
import { buildMetadata, pageSeo } from "@/lib/seo";
export const metadata: Metadata = buildMetadata(pageSeo["/automations"]);
export default function AutomationsPage() {
  return <div className="rebuild-page">
    <section className="rebuild-hero"><p className="rebuild-kicker">Automation</p><h1>Make the next step easier to follow through.</h1><p className="rebuild-lead">When a process is clear, automation can reduce repetitive work. We scope the triggers, actions and review steps around the tools your team actually uses.</p><Link className="rebuild-button" href="/contact?service=crm">Discuss your workflow</Link></section>
    <section className="rebuild-section"><h2 className="rebuild-section-heading">Start with one useful task.</h2><div className="rebuild-grid rebuild-grid-two"><article className="rebuild-panel"><h3>Enquiry routing</h3><p>Send a new enquiry to the agreed owner with the information they need to act.</p></article><article className="rebuild-panel"><h3>Follow-up tasks</h3><p>Create reminders when an opportunity reaches a defined stage or needs attention.</p></article><article className="rebuild-panel"><h3>Team notifications</h3><p>Notify the right person about an agreed change, without asking someone to copy the same details between tools.</p></article><article className="rebuild-panel"><h3>Customer messages</h3><p>Plan acknowledgments and follow-up where the purpose, permissions and stopping rules are clear.</p></article></div><p>These are examples to discuss, not a promise that every workflow is included in every project.</p></section>
    <section className="rebuild-section"><h2 className="rebuild-section-heading">Define the rules before switching it on.</h2><ol className="rebuild-list"><li>Agree the trigger and the information it needs.</li><li>Choose the action, owner and exceptions.</li><li>Test expected and failed journeys with suitable test data.</li><li>Confirm who reviews the results and handles issues.</li></ol></section>
    <section className="rebuild-section"><h2 className="rebuild-section-heading">Keep the scope and costs clear.</h2><p>We agree the number of workflows, connected systems and support needs in your proposal. Software licences, email or SMS usage and custom integrations may be separate costs.</p><p>If your records or process need work first, start with the CRM. A website and CRM built together can include the core enquiry connection in the agreed scope.</p><Link className="rebuild-text-link" href="/crm">CRM projects →</Link>{" "}<Link className="rebuild-text-link" href="/connected">Website + CRM →</Link></section>
    <section className="rebuild-section"><h2 className="rebuild-section-heading">Which task is slowing your team down?</h2><p>Tell us what starts the task, who handles it and where the work gets stuck.</p><Link className="rebuild-button" href="/contact?service=crm">Discuss your workflow</Link></section>
  </div>;
}
